import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import { User } from '../models/User';
import { Listing } from '../models/Listing';
import { Review } from '../models/Review';
import { Amenity } from '../models/Amenity';
import { config } from '../config/env';

const sampleAmenities = [
  { name: 'Mountain view', category: 'Scenic views', icon: 'Mountain', description: 'Unobstructed mountain view' },
  { name: 'Sea view', category: 'Scenic views', icon: 'Sun', description: 'Panoramic ocean & sea view' },
  { name: 'Fast Wifi', category: 'Internet and office', icon: 'Wifi', description: '500 Mbps speed test verified' },
  { name: 'Dedicated workspace', category: 'Internet and office', icon: 'Laptop', description: 'Ergonomic chair & desk' },
  { name: 'Free parking on premises', category: 'Parking and facilities', icon: 'Car', description: '2 space private driveway' },
  { name: 'Private hot tub', category: 'Bathroom & Facilities', icon: 'Bath', description: 'Heated outdoor hot tub' },
  { name: 'Swimming pool', category: 'Outdoor', icon: 'Sun', description: 'Private temperature-controlled pool' },
  { name: 'Chef Kitchen', category: 'Kitchen and dining', icon: 'Utensils', description: 'Fully equipped kitchen with gourmet appliances' },
  { name: 'Patio or balcony', category: 'Outdoor', icon: 'Sun', description: 'Private deck with outdoor lounge chairs' },
  { name: 'Indoor fireplace', category: 'Heating and cooling', icon: 'Flame', description: 'Wood-burning fireplace with logs provided' },
  { name: 'HDTV with Netflix', category: 'Entertainment', icon: 'Tv', description: '65 inch 4K OLED TV' },
  { name: 'Central air conditioning', category: 'Heating and cooling', icon: 'Wind', description: 'Dual-zone climate control' },
  { name: 'Washer & Dryer', category: 'Bedroom and laundry', icon: 'Shirt', description: 'In-unit high efficiency washer and dryer' },
  { name: 'EV Charger', category: 'Parking and facilities', icon: 'Zap', description: 'Level 2 EV charger' },
  { name: 'Self check-in', category: 'Services', icon: 'Key', description: 'Keypad smart lock' },
];

const allListings = [
  // ===================== PUNE (5 places) =====================
  {
    title: 'Flat in Pashan',
    location: 'Pashan, Pune, Maharashtra, India',
    city: 'Pune',
    country: 'India',
    latitude: 18.5416,
    longitude: 73.7924,
    propertyType: 'Entire rental unit',
    description: 'Charming modern flat in Pashan with peaceful greenery, high-speed WiFi, spacious balcony, and designer living interiors.',
    host: {
      name: 'Rohan Sharma',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 5 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.96,
    reviewCount: 42,
    pricePerNight: 4087,
    cleaningFee: 500,
    serviceFee: 300,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Flat in Wadgaon Sheri',
    location: 'Wadgaon Sheri, Pune, Maharashtra, India',
    city: 'Pune',
    country: 'India',
    latitude: 18.5529,
    longitude: 73.9242,
    propertyType: 'Entire apartment',
    description: 'Stylish 1BHK apartment near IT parks with minimal boho decor, fully functional kitchen, and private parking space.',
    host: {
      name: 'Priya Kulkarni',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 4 years hosting',
      responseRate: 98,
      responseTime: 'within an hour',
    },
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.93,
    reviewCount: 35,
    pricePerNight: 5136,
    cleaningFee: 600,
    serviceFee: 400,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Flat in Viman Nagar',
    location: 'Viman Nagar, Pune, Maharashtra, India',
    city: 'Pune',
    country: 'India',
    latitude: 18.5679,
    longitude: 73.9143,
    propertyType: 'Entire rental unit',
    description: 'Sunlit modern flat steps away from Phoenix Marketcity Mall with high-speed WiFi, smart TV, and mountain sunrise views.',
    host: {
      name: 'Aarav Mehta',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 6 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.96,
    reviewCount: 58,
    pricePerNight: 5250,
    cleaningFee: 700,
    serviceFee: 450,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Penthouse in Koregaon Park',
    location: 'Koregaon Park, Pune, Maharashtra, India',
    city: 'Pune',
    country: 'India',
    latitude: 18.5362,
    longitude: 73.894,
    propertyType: 'Luxury penthouse',
    description: 'Ultra-luxurious penthouse with private terrace garden, chic nightlife access, smart home controls, and tree-lined neighborhood vistas.',
    host: {
      name: 'Vikram Joshi',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 3 years hosting',
      responseRate: 99,
      responseTime: 'within a few hours',
    },
    guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.91,
    reviewCount: 44,
    pricePerNight: 8900,
    cleaningFee: 1000,
    serviceFee: 650,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Villa in Baner Hill',
    location: 'Baner, Pune, Maharashtra, India',
    city: 'Pune',
    country: 'India',
    latitude: 18.559,
    longitude: 73.7868,
    propertyType: 'Entire villa',
    description: 'Tranquil hillside villa featuring private lawn, outdoor dining deck, workstation with high-speed internet, and hill views.',
    host: {
      name: 'Ananya Deshmukh',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 4 years hosting',
      responseRate: 97,
      responseTime: 'within an hour',
    },
    guests: 5,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600573472591-ee6c563aaec9?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.88,
    reviewCount: 39,
    pricePerNight: 7200,
    cleaningFee: 800,
    serviceFee: 500,
    available: true,
    isGuestFavorite: true,
  },

  // ===================== MUMBAI (5 places) =====================
  {
    title: 'Sea View Suite in Marine Drive',
    location: 'Marine Drive, Mumbai, Maharashtra, India',
    city: 'Mumbai',
    country: 'India',
    latitude: 18.9438,
    longitude: 72.823,
    propertyType: 'Luxury apartment',
    description: 'Iconic Arabian Sea view apartment on Queen\'s Necklace with heritage high ceilings, marble floors, and concierge service.',
    host: {
      name: 'Kabir Singhania',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 8 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.98,
    reviewCount: 95,
    pricePerNight: 12500,
    cleaningFee: 1200,
    serviceFee: 900,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Boho Flat in Bandra West',
    location: 'Bandra West, Mumbai, Maharashtra, India',
    city: 'Mumbai',
    country: 'India',
    latitude: 19.0596,
    longitude: 72.8295,
    propertyType: 'Entire apartment',
    description: 'Chic bohemian apartment located in the artful heart of Bandra, minutes from trendy cafes, Pali Hill, and Carter Road promenade.',
    host: {
      name: 'Rhea Sen',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 4 years hosting',
      responseRate: 99,
      responseTime: 'within an hour',
    },
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.94,
    reviewCount: 67,
    pricePerNight: 8500,
    cleaningFee: 800,
    serviceFee: 600,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Beachfront Condo in Juhu',
    location: 'Juhu Beach, Mumbai, Maharashtra, India',
    city: 'Mumbai',
    country: 'India',
    latitude: 19.1075,
    longitude: 72.8263,
    propertyType: 'Entire condo',
    description: 'Direct sunset beach views over Juhu waters with expansive glass windows, private parking, and premium kitchen amenities.',
    host: {
      name: 'Siddharth Roy',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 6 years hosting',
      responseRate: 98,
      responseTime: 'within an hour',
    },
    guests: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.92,
    reviewCount: 53,
    pricePerNight: 11000,
    cleaningFee: 1000,
    serviceFee: 800,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Heritage Flat in Colaba',
    location: 'Colaba Causeway, Mumbai, Maharashtra, India',
    city: 'Mumbai',
    country: 'India',
    latitude: 18.9067,
    longitude: 72.8147,
    propertyType: 'Historical home',
    description: 'Colonial style high-ceiling flat 2 minutes walk from Gateway of India, art galleries, and historic South Mumbai monuments.',
    host: {
      name: 'Tara Merchant',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      isSuperhost: false,
      joinedDate: '3 years hosting',
      responseRate: 96,
      responseTime: 'within a few hours',
    },
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.87,
    reviewCount: 31,
    pricePerNight: 7800,
    cleaningFee: 700,
    serviceFee: 500,
    available: true,
    isGuestFavorite: false,
  },
  {
    title: 'High-Rise Studio in Powai',
    location: 'Hiranandani Gardens, Powai, Mumbai, India',
    city: 'Mumbai',
    country: 'India',
    latitude: 19.1197,
    longitude: 72.905,
    propertyType: 'Serviced apartment',
    description: 'Modern luxury studio overlooking Powai Lake with access to club swimming pool, gym, and neoclassical promenade.',
    host: {
      name: 'Nikhil Verma',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 5 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.95,
    reviewCount: 72,
    pricePerNight: 6200,
    cleaningFee: 600,
    serviceFee: 400,
    available: true,
    isGuestFavorite: true,
  },

  // ===================== GOA (5 places) =====================
  {
    title: 'Beachfront Villa in Calangute',
    location: 'Calangute Beach, Goa, India',
    city: 'Goa',
    country: 'India',
    latitude: 15.5494,
    longitude: 73.7535,
    propertyType: 'Entire villa',
    description: 'Lush tropical villa with private swimming pool, hammock deck, outdoor barbecue grill, and direct beach access path.',
    host: {
      name: 'Natasha D\'Souza',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 7 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 8,
    bedrooms: 4,
    beds: 4,
    bathrooms: 4,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.97,
    reviewCount: 110,
    pricePerNight: 14500,
    cleaningFee: 1500,
    serviceFee: 1000,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Pool Cottage in Anjuna',
    location: 'Anjuna Beach, Goa, India',
    city: 'Goa',
    country: 'India',
    latitude: 15.587,
    longitude: 73.7412,
    propertyType: 'Cottage',
    description: 'Serene Portuguese cottage nestled in coconut groves with private plunge pool, outdoor rain shower, and eco garden.',
    host: {
      name: 'Zoe Fernandes',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 4 years hosting',
      responseRate: 99,
      responseTime: 'within an hour',
    },
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.96,
    reviewCount: 84,
    pricePerNight: 9200,
    cleaningFee: 900,
    serviceFee: 650,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Portuguese Home in Panaji',
    location: 'Fontainhas, Panaji, Goa, India',
    city: 'Goa',
    country: 'India',
    latitude: 15.4989,
    longitude: 73.8278,
    propertyType: 'Historical home',
    description: 'Vibrant yellow 19th-century Portuguese heritage bungalow in Latin Quarter of Panaji with azulejo tile artwork and patio.',
    host: {
      name: 'Mario Pinto',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 6 years hosting',
      responseRate: 98,
      responseTime: 'within an hour',
    },
    guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600573472591-ee6c563aaec9?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.93,
    reviewCount: 62,
    pricePerNight: 8800,
    cleaningFee: 850,
    serviceFee: 600,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Modern Resort Suite in Candolim',
    location: 'Candolim, Goa, India',
    city: 'Goa',
    country: 'India',
    latitude: 15.518,
    longitude: 73.763,
    propertyType: 'Resort suite',
    description: 'Sun-drenched luxury apartment featuring resort lagoon pool, poolside cocktail lounge, and 5-minute walk to Candolim sea.',
    host: {
      name: 'Rahul Miranda',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      isSuperhost: false,
      joinedDate: '2 years hosting',
      responseRate: 95,
      responseTime: 'within a few hours',
    },
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.89,
    reviewCount: 45,
    pricePerNight: 6500,
    cleaningFee: 600,
    serviceFee: 450,
    available: true,
    isGuestFavorite: false,
  },
  {
    title: 'Cliffside Eco Sanctuary in Palolem',
    location: 'Palolem Beach, South Goa, India',
    city: 'Goa',
    country: 'India',
    latitude: 15.01,
    longitude: 74.023,
    propertyType: 'Eco lodge',
    description: 'Panoramic clifftop retreat overlooking Palolem bay with wooden sundeck, open-air bath tub, and dolphin sighting views.',
    host: {
      name: 'Maya Alvares',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 5 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.99,
    reviewCount: 97,
    pricePerNight: 10500,
    cleaningFee: 900,
    serviceFee: 700,
    available: true,
    isGuestFavorite: true,
  },

  // ===================== BENGALURU (5 places) =====================
  {
    title: 'Tech Studio in Indiranagar',
    location: '100ft Road, Indiranagar, Bengaluru, India',
    city: 'Bengaluru',
    country: 'India',
    latitude: 12.9784,
    longitude: 77.6408,
    propertyType: 'Entire apartment',
    description: 'Ultra-modern tech-ready studio apartment on famous 100ft road with standing desk, dual monitors, fiber internet, and rooftop coffee bar.',
    host: {
      name: 'Aditya Rao',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 5 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.95,
    reviewCount: 78,
    pricePerNight: 4800,
    cleaningFee: 500,
    serviceFee: 350,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Luxury Flat in Koramangala',
    location: '5th Block, Koramangala, Bengaluru, India',
    city: 'Bengaluru',
    country: 'India',
    latitude: 12.9352,
    longitude: 77.6245,
    propertyType: 'Entire rental unit',
    description: 'Spacious 2BHK designer home near startup hubs, artisanal bakeries, and craft breweries with private sunlit balcony.',
    host: {
      name: 'Kavya Nair',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 4 years hosting',
      responseRate: 99,
      responseTime: 'within an hour',
    },
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.92,
    reviewCount: 54,
    pricePerNight: 5500,
    cleaningFee: 600,
    serviceFee: 400,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Penthouse Suite in Whitefield',
    location: 'ITPL Main Road, Whitefield, Bengaluru, India',
    city: 'Bengaluru',
    country: 'India',
    latitude: 12.9698,
    longitude: 77.7499,
    propertyType: 'Luxury penthouse',
    description: 'Executive penthouse overlooking tech park skyline with private Jacuzzi, indoor fireplace, and 24/7 security guard.',
    host: {
      name: 'Siddharth Hegde',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 6 years hosting',
      responseRate: 98,
      responseTime: 'within an hour',
    },
    guests: 5,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.90,
    reviewCount: 41,
    pricePerNight: 8200,
    cleaningFee: 900,
    serviceFee: 600,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Garden Villa near MG Road',
    location: 'Lavelle Road, MG Road, Bengaluru, India',
    city: 'Bengaluru',
    country: 'India',
    latitude: 12.9716,
    longitude: 77.5946,
    propertyType: 'Entire villa',
    description: 'Lush heritage bungalow oasis in central Bengaluru surrounded by ancient rain trees, private courtyard, and teak furniture.',
    host: {
      name: 'Padmini Gowda',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      isSuperhost: false,
      joinedDate: '3 years hosting',
      responseRate: 96,
      responseTime: 'within a few hours',
    },
    guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.88,
    reviewCount: 36,
    pricePerNight: 9500,
    cleaningFee: 1000,
    serviceFee: 700,
    available: true,
    isGuestFavorite: false,
  },
  {
    title: 'Cozy Suite in HSR Layout',
    location: 'Sector 1, HSR Layout, Bengaluru, India',
    city: 'Bengaluru',
    country: 'India',
    latitude: 12.9121,
    longitude: 77.6446,
    propertyType: 'Entire apartment',
    description: 'Minimalist Scandinavian style 1BHK with smart TV, fast WiFi, fully automated kitchen, and quiet residential surroundings.',
    host: {
      name: 'Varun Menon',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 4 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.96,
    reviewCount: 63,
    pricePerNight: 4200,
    cleaningFee: 450,
    serviceFee: 300,
    available: true,
    isGuestFavorite: true,
  },

  // ===================== DELHI (5 places) =====================
  {
    title: 'Heritage Flat in Hauz Khas Village',
    location: 'Hauz Khas Village, New Delhi, India',
    city: 'Delhi',
    country: 'India',
    latitude: 28.5494,
    longitude: 77.196,
    propertyType: 'Historical home',
    description: 'Artistic sanctuary overlooking 13th-century medieval lake reservoir and deer park with bohemian rooftop deck.',
    host: {
      name: 'Kabir Malhotra',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 6 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.97,
    reviewCount: 89,
    pricePerNight: 7500,
    cleaningFee: 700,
    serviceFee: 500,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Luxury Apartment in South Extension',
    location: 'South Extension II, New Delhi, India',
    city: 'Delhi',
    country: 'India',
    latitude: 28.5683,
    longitude: 77.2211,
    propertyType: 'Entire apartment',
    description: 'Elegant South Delhi residence near premier markets and metro station with plush Italian leather sofa and chef kitchen.',
    host: {
      name: 'Simran Khurana',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 5 years hosting',
      responseRate: 99,
      responseTime: 'within an hour',
    },
    guests: 5,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.93,
    reviewCount: 52,
    pricePerNight: 8900,
    cleaningFee: 850,
    serviceFee: 600,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Modern Suite in Connaught Place',
    location: 'Connaught Place, New Delhi, India',
    city: 'Delhi',
    country: 'India',
    latitude: 28.6315,
    longitude: 77.2167,
    propertyType: 'Serviced apartment',
    description: 'Heart of Central Delhi luxury apartment steps from Janpath, India Gate, museum quarters, and fine dining hotspots.',
    host: {
      name: 'Arjun Kapoor',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 7 years hosting',
      responseRate: 100,
      responseTime: 'within an hour',
    },
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.94,
    reviewCount: 76,
    pricePerNight: 6800,
    cleaningFee: 650,
    serviceFee: 450,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Golf View Penthouse in Gurgaon',
    location: 'Golf Course Road, Gurgaon, NCR, India',
    city: 'Delhi',
    country: 'India',
    latitude: 28.4595,
    longitude: 77.0266,
    propertyType: 'Luxury penthouse',
    description: 'Sky penthouse on Golf Course Road with private swimming pool, panoramic green course views, and smart home automation.',
    host: {
      name: 'Rohan Oberoi',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      isSuperhost: true,
      joinedDate: 'Superhost · 4 years hosting',
      responseRate: 98,
      responseTime: 'within an hour',
    },
    guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.91,
    reviewCount: 48,
    pricePerNight: 12000,
    cleaningFee: 1200,
    serviceFee: 850,
    available: true,
    isGuestFavorite: true,
  },
  {
    title: 'Garden Villa in Vasant Kunj',
    location: 'Vasant Kunj, New Delhi, India',
    city: 'Delhi',
    country: 'India',
    latitude: 28.5293,
    longitude: 77.1539,
    propertyType: 'Entire villa',
    description: 'Sprawling green villa near South Delhi malls and airport with private garden lawn, gazebo, and dedicated butler service.',
    host: {
      name: 'Meera Chawla',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80',
      isSuperhost: false,
      joinedDate: '2 years hosting',
      responseRate: 94,
      responseTime: 'within a few hours',
    },
    guests: 8,
    bedrooms: 4,
    beds: 4,
    bathrooms: 4,
    amenities: sampleAmenities,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600573472591-ee6c563aaec9?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.88,
    reviewCount: 33,
    pricePerNight: 13500,
    cleaningFee: 1300,
    serviceFee: 950,
    available: true,
    isGuestFavorite: false,
  },
];

const sampleReviews = [
  {
    authorName: 'Sarah Jenkins',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'Absolutely breathtaking! The photos do not even do it justice. Sitting on the balcony during sunset was pure magic. Thoughtful hosts!',
    createdAt: new Date('2025-08-15'),
  },
  {
    authorName: 'Marcus Chen',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'High-speed internet made remote work effortless, and the neighborhood is so peaceful and safe.',
    createdAt: new Date('2025-07-22'),
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(config.mongodbUri);
    console.log('Connected to MongoDB for seeding...');

    await User.deleteMany({});
    await Listing.deleteMany({});
    await Review.deleteMany({});
    await Amenity.deleteMany({});

    console.log('Cleared old database records.');

    await Amenity.insertMany(sampleAmenities);
    console.log('Seeded amenities.');

    const passwordHash = await bcrypt.hash('password123', 10);
    const user = await User.create({
      name: 'Alex Johnson',
      email: 'alex@example.com',
      passwordHash,
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=250&q=80',
    });
    console.log(`Seeded demo user: ${user.email} (password: password123)`);

    const createdListings = await Listing.insertMany(allListings);
    console.log(`Seeded ${createdListings.length} listings across 5 destinations!`);

    // Attach sample reviews to the first few listings
    const reviewsToInsert = [];
    for (let i = 0; i < Math.min(createdListings.length, 5); i++) {
      reviewsToInsert.push(
        ...sampleReviews.map((r) => ({
          ...r,
          listing: createdListings[i]._id,
          user: user._id,
        }))
      );
    }

    await Review.insertMany(reviewsToInsert);
    console.log(`Seeded ${reviewsToInsert.length} reviews across listings.`);

    console.log('=================================');
    console.log('🎉 Database seeding completed successfully!');
    console.log(`Summary: 25 listings (5 per city: Pune, Mumbai, Goa, Bengaluru, Delhi)`);
    console.log('=================================');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDB();
